services:
  mongodb: 
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devjoemar
      - MONGO_INITDB_ROOT_PASSWORD=Password123
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=devjoemar
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Password123
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: {}